package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

// AgentsMDTranslator generates a committed AGENTS.md file that follows the
// Linux Foundation / AAIF standard. Unlike other translators, its output is
// committed to version control so that any AI tool can read it without ajolote.
type AgentsMDTranslator struct{}

func (t *AgentsMDTranslator) Name() string        { return "agents-md" }
func (t *AgentsMDTranslator) Committed() bool     { return true }
func (t *AgentsMDTranslator) OutputFiles() []string { return []string{"AGENTS.md"} }

func (t *AgentsMDTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "AGENTS.md", t.renderAGENTSmd(cfg, projectRoot)); err != nil {
		return fmt.Errorf("agents-md: %w", err)
	}
	return nil
}

// Import reads an existing AGENTS.md that was not generated by ajolote and
// returns its content as a rule file. This lets teams with an existing AGENTS.md
// bootstrap ajolote without losing their instructions.
func (t *AgentsMDTranslator) Import(projectRoot string) (*ImportResult, error) {
	agentsMD := filepath.Join(projectRoot, "AGENTS.md")
	data, err := os.ReadFile(agentsMD)
	if err != nil {
		if os.IsNotExist(err) {
			return &ImportResult{}, nil
		}
		return nil, fmt.Errorf("reading AGENTS.md: %w", err)
	}
	content := string(data)
	if isAjoloteGenerated(content) {
		return &ImportResult{}, nil
	}
	return &ImportResult{
		NewRuleFiles: map[string]string{"general.md": content},
	}, nil
}

func (t *AgentsMDTranslator) renderAGENTSmd(cfg *config.Config, projectRoot string) string {
	var sb strings.Builder
	// HTML comment so the marker is invisible in rendered Markdown
	sb.WriteString("<!-- AGENTS.md — Generated by ajolote-ai from `.agents/config.json`. ")
	sb.WriteString("Commit this file; it is the canonical instruction file read by any AAIF-compatible tool. ")
	sb.WriteString("Edit `.agents/` source files and run `ajolote sync` to regenerate. -->\n\n")
	sb.WriteString(inlineFiles("Rules", projectRoot, cfg.Rules))
	sb.WriteString(inlineFiles("Skills", projectRoot, cfg.Skills))
	sb.WriteString(inlineFiles("Personas", projectRoot, personaPaths(cfg.Personas)))
	sb.WriteString(inlineFiles("Context", projectRoot, cfg.Context))
	return sb.String()
}
