package translators

import (
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type AiderTranslator struct{}

func (t *AiderTranslator) Name() string { return "aider" }

func (t *AiderTranslator) OutputFiles() []string {
	return []string{".aider.conf.yml"}
}

func (t *AiderTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".aider.conf.yml", t.renderConf(cfg)); err != nil {
		return fmt.Errorf("aider: %w", err)
	}
	return nil
}

func (t *AiderTranslator) renderConf(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString("# Project context\n")
	sb.WriteString(fmt.Sprintf("# Name: %s\n", cfg.Project.Name))
	sb.WriteString(fmt.Sprintf("# Stack: %s\n", cfg.Project.Stack))
	sb.WriteString(fmt.Sprintf("# Language: %s\n", cfg.Project.Language))
	sb.WriteString(fmt.Sprintf("# Test runner: %s\n\n", cfg.Project.TestRunner))

	// Aider reads a system prompt from a file via --system-prompt.
	// We write the rules as a read-only context file aider will pick up.
	sb.WriteString("# Rules summary (for reference):\n")
	for _, rule := range cfg.Rules.General {
		sb.WriteString(fmt.Sprintf("#   - %s\n", rule))
	}
	sb.WriteString("\n")
	sb.WriteString("# aider configuration\n")
	sb.WriteString("auto-commits: false\n")
	sb.WriteString("gitignore: false\n")

	return sb.String()
}
