package translators

import (
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type AiderTranslator struct{}

func (t *AiderTranslator) Name() string { return "aider" }

func (t *AiderTranslator) OutputFiles() []string {
	return []string{".aider.conf.yml"}
}

func (t *AiderTranslator) Import(projectRoot string) (*ImportResult, error) {
	return &ImportResult{}, nil // no structured config to import
}

func (t *AiderTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".aider.conf.yml", t.renderConf(cfg)); err != nil {
		return fmt.Errorf("aider: %w", err)
	}
	return nil
}

func (t *AiderTranslator) renderConf(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString("# aider configuration\n")
	sb.WriteString("auto-commits: false\n")
	sb.WriteString("gitignore: false\n")

	// Collect all agent files — Aider reads them natively as context
	var readFiles []string
	readFiles = append(readFiles, cfg.Rules...)
	readFiles = append(readFiles, cfg.Skills...)
	readFiles = append(readFiles, personaPaths(cfg.Personas)...)
	readFiles = append(readFiles, cfg.Context...)
	for _, sr := range cfg.ScopedRules {
		readFiles = append(readFiles, sr.Path)
	}

	if len(readFiles) > 0 {
		sb.WriteString("\n# Files to include as context\nread:\n")
		for _, f := range readFiles {
			sb.WriteString(fmt.Sprintf("  - %s\n", f))
		}
	}
	return sb.String()
}
