package translators

import (
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type AiderTranslator struct{}

func (t *AiderTranslator) Name() string { return "aider" }

func (t *AiderTranslator) OutputFiles() []string {
	return []string{".aider.conf.yml"}
}

func (t *AiderTranslator) Import(projectRoot string) (*ImportResult, error) {
	return &ImportResult{}, nil // no structured config to import
}

func (t *AiderTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".aider.conf.yml", t.renderConf(cfg)); err != nil {
		return fmt.Errorf("aider: %w", err)
	}
	return nil
}

func (t *AiderTranslator) renderConf(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString("# Rules files:\n")
	for _, r := range cfg.Rules {
		sb.WriteString(fmt.Sprintf("#   %s\n", r))
	}
	sb.WriteString("\n")
	sb.WriteString("# aider configuration\n")
	sb.WriteString("auto-commits: false\n")
	sb.WriteString("gitignore: false\n")
	return sb.String()
}
