package translators

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClaudeTranslator struct{}

func (t *ClaudeTranslator) Name() string { return "claude" }

func (t *ClaudeTranslator) OutputFiles() []string {
	// .claude/commands/ covers ajolote-sync.md and all generated command files
	return []string{"CLAUDE.md", ".claude/settings.json", ".claude/commands/"}
}

func (t *ClaudeTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "CLAUDE.md", t.renderCLAUDEmd(cfg)); err != nil {
		return fmt.Errorf("claude: %w", err)
	}
	if err := writeFile(projectRoot, ".claude/settings.json", t.renderSettings(cfg)); err != nil {
		return fmt.Errorf("claude settings: %w", err)
	}
	if err := writeFile(projectRoot, ".claude/commands/ajolote-sync.md", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("claude slash command: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		if err := writeFile(projectRoot, ".claude/commands/"+cmd.Name+".md", cmd.Content); err != nil {
			return fmt.Errorf("claude command %s: %w", cmd.Name, err)
		}
	}
	return nil
}

func (t *ClaudeTranslator) Import(projectRoot string) (*ImportResult, error) {
	claudeDir := filepath.Join(projectRoot, ".claude")
	if _, err := os.Stat(claudeDir); os.IsNotExist(err) {
		return nil, nil // Claude not present in this project
	}

	servers, err := parseMCPFile(filepath.Join(claudeDir, "settings.json"))
	if err != nil {
		return nil, err
	}

	existing, err := existingCommandNames(projectRoot)
	if err != nil {
		return nil, err
	}

	skip := map[string]bool{"ajolote-sync": true}
	cmds, err := importCommandFiles(filepath.Join(claudeDir, "commands"), ".md", skip, existing, func(name, raw string) Command {
		desc, body := parseFrontmatter(raw)
		return Command{Name: name, Description: desc, Content: body}
	})
	if err != nil {
		return nil, err
	}

	return &ImportResult{NewMCPServers: servers, NewCommands: cmds}, nil
}

func (t *ClaudeTranslator) renderSlashCommand() string {
	return `Run the following shell command to sync your Claude Code configuration with the shared team config:

` + "```" + `
ajolote sync claude
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .claude/settings.json into .agents/config.json
- ↓ Regenerates CLAUDE.md and .claude/settings.json from the updated canonical config

If .agents/config.json was updated, review the diff and commit it so your teammates receive the changes.
`
}

func (t *ClaudeTranslator) renderCLAUDEmd(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# CLAUDE.md\n\n")
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(fileListMarkdown("Rules", cfg.Rules))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}

func (t *ClaudeTranslator) renderSettings(cfg *config.Config) string {
	type settings struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	s := settings{MCPServers: cfg.MCP.Servers}
	if s.MCPServers == nil {
		s.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(s, "", "  ")
	return string(data) + "\n"
}
