package translators

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClaudeTranslator struct{}

func (t *ClaudeTranslator) Name() string { return "claude" }

func (t *ClaudeTranslator) OutputFiles() []string {
	return []string{"CLAUDE.md", ".claude/settings.json", ".claude/commands/ajolote-sync.md"}
}

func (t *ClaudeTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "CLAUDE.md", t.renderCLAUDEmd(cfg)); err != nil {
		return fmt.Errorf("claude: %w", err)
	}
	if err := writeFile(projectRoot, ".claude/settings.json", t.renderSettings(cfg)); err != nil {
		return fmt.Errorf("claude settings: %w", err)
	}
	if err := writeFile(projectRoot, ".claude/commands/ajolote-sync.md", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("claude slash command: %w", err)
	}
	return nil
}

func (t *ClaudeTranslator) Import(projectRoot string) (*ImportResult, error) {
	servers, err := parseMCPFile(filepath.Join(projectRoot, ".claude", "settings.json"))
	if err != nil {
		return nil, err
	}
	if servers == nil {
		return nil, nil // file doesn't exist
	}
	return &ImportResult{NewMCPServers: servers}, nil
}

func (t *ClaudeTranslator) renderSlashCommand() string {
	return `Run the following shell command to sync your Claude Code configuration with the shared team config:

` + "```" + `
ajolote sync claude
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .claude/settings.json into .agents/config.json
- ↓ Regenerates CLAUDE.md and .claude/settings.json from the updated canonical config

If .agents/config.json was updated, review the diff and commit it so your teammates receive the changes.
`
}

func (t *ClaudeTranslator) renderCLAUDEmd(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# CLAUDE.md\n\n")
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString("---\n\n")

	sb.WriteString("## Project\n\n")
	sb.WriteString(fmt.Sprintf("- **Name:** %s\n", cfg.Project.Name))
	sb.WriteString(fmt.Sprintf("- **Language:** %s\n", cfg.Project.Language))
	sb.WriteString(fmt.Sprintf("- **Stack:** %s\n", cfg.Project.Stack))
	sb.WriteString(fmt.Sprintf("- **Repo type:** %s\n", cfg.Project.RepoType))
	sb.WriteString(fmt.Sprintf("- **Test runner:** %s\n\n", cfg.Project.TestRunner))

	sb.WriteString("## Agent Rules\n\n")
	sb.WriteString(rulesMarkdown(cfg))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))

	return sb.String()
}

func (t *ClaudeTranslator) renderSettings(cfg *config.Config) string {
	type settings struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	s := settings{MCPServers: cfg.MCP.Servers}
	if s.MCPServers == nil {
		s.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(s, "", "  ")
	return string(data) + "\n"
}
