package translators

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClaudeTranslator struct{}

func (t *ClaudeTranslator) Name() string { return "claude" }

func (t *ClaudeTranslator) OutputFiles() []string {
	// .claude/commands/ covers ajolote-sync.md and all generated command files
	// .claude/rules/ covers scoped rule files
	// .claude/agents/ covers persona subagent files (only written when claude: block is present)
	return []string{"CLAUDE.md", ".claude/settings.json", ".claude/commands/", ".claude/rules/", ".claude/agents/"}
}

func (t *ClaudeTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "CLAUDE.md", t.renderCLAUDEmd(cfg)); err != nil {
		return fmt.Errorf("claude: %w", err)
	}
	if err := writeFile(projectRoot, ".claude/settings.json", t.renderSettings(cfg)); err != nil {
		return fmt.Errorf("claude settings: %w", err)
	}
	// Write user-scoped servers to ~/.claude.json (merged, never overwrites existing)
	if userServers := userScopedServers(cfg.MCP.Servers); len(userServers) > 0 {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("resolving home directory: %w", err)
		}
		if err := mergeUserMCPConfig(filepath.Join(home, ".claude.json"), userServers); err != nil {
			return fmt.Errorf("writing user MCP config (~/.claude.json): %w", err)
		}
	}
	if err := writeFile(projectRoot, ".claude/commands/ajolote-sync.md", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("claude slash command: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		if err := writeFile(projectRoot, ".claude/commands/"+cmd.Name+".md", cmd.Content); err != nil {
			return fmt.Errorf("claude command %s: %w", cmd.Name, err)
		}
	}
	for _, sr := range cfg.ScopedRules {
		content := fmt.Sprintf("---\ndescription: %s\nglobs: %s\n---\n\n@%s\n",
			sr.Name, strings.Join(sr.Globs, ", "), sr.Path)
		if err := writeFile(projectRoot, ".claude/rules/"+sr.Name+".md", content); err != nil {
			return fmt.Errorf("claude scoped rule %s: %w", sr.Name, err)
		}
	}
	for _, persona := range cfg.Personas {
		if persona.Claude == nil {
			continue
		}
		name := agentName(persona.Path)
		content := t.renderAgentFile(persona, projectRoot)
		if err := writeFile(projectRoot, ".claude/agents/"+name+".md", content); err != nil {
			return fmt.Errorf("claude agent %s: %w", name, err)
		}
	}
	return nil
}

func (t *ClaudeTranslator) Import(projectRoot string) (*ImportResult, error) {
	claudeDir := filepath.Join(projectRoot, ".claude")
	claudeMDPath := filepath.Join(projectRoot, "CLAUDE.md")

	// Require at least .claude/ dir or CLAUDE.md to be present
	_, claudeDirErr := os.Stat(claudeDir)
	_, claudeMDErr := os.Stat(claudeMDPath)
	if os.IsNotExist(claudeDirErr) && os.IsNotExist(claudeMDErr) {
		return nil, nil // Claude not present in this project
	}

	result := &ImportResult{}

	// Import MCP servers and commands from .claude/ if it exists
	if !os.IsNotExist(claudeDirErr) {
		servers, err := parseMCPFile(filepath.Join(claudeDir, "settings.json"))
		if err != nil {
			return nil, err
		}
		result.NewMCPServers = servers

		existing, err := existingCommandNames(projectRoot)
		if err != nil {
			return nil, err
		}

		skip := map[string]bool{"ajolote-sync": true}
		cmds, err := importCommandFiles(filepath.Join(claudeDir, "commands"), ".md", skip, existing, func(name, raw string) Command {
			desc, body := parseFrontmatter(raw)
			return Command{Name: name, Description: desc, Content: body}
		})
		if err != nil {
			return nil, err
		}
		result.NewCommands = cmds
	}

	// Import CLAUDE.md content as a rule file if it was not generated by ajolote
	if !os.IsNotExist(claudeMDErr) {
		data, err := os.ReadFile(claudeMDPath)
		if err != nil {
			return nil, fmt.Errorf("reading CLAUDE.md: %w", err)
		}
		if content := string(data); !isAjoloteGenerated(content) {
			result.NewRuleFiles = map[string]string{"general.md": content}
		}
	}

	return result, nil
}

func (t *ClaudeTranslator) renderSlashCommand() string {
	return `Run the following shell command to sync your Claude Code configuration with the shared team config:

` + "```" + `
ajolote sync claude
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .claude/settings.json into .agents/config.json
- ↓ Regenerates CLAUDE.md and .claude/settings.json from the updated canonical config

If .agents/config.json was updated, review the diff and commit it so your teammates receive the changes.
`
}

func (t *ClaudeTranslator) renderCLAUDEmd(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# CLAUDE.md\n\n")
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(atFileList("Rules", cfg.Rules))
	sb.WriteString(atFileList("Skills", cfg.Skills))
	sb.WriteString(atFileList("Personas", personaPaths(cfg.Personas)))
	sb.WriteString(atFileList("Context", cfg.Context))
	return sb.String()
}

func (t *ClaudeTranslator) renderAgentFile(persona config.Persona, projectRoot string) string {
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString("name: " + toTitle(agentName(persona.Path)) + "\n")

	desc := persona.Claude.Description
	if desc == "" {
		desc = extractFirstParagraph(filepath.Join(projectRoot, persona.Path))
	}
	if desc != "" {
		sb.WriteString("description: " + desc + "\n")
	}
	if persona.Claude.Model != "" {
		sb.WriteString("model: " + resolveModel(persona.Claude.Model) + "\n")
	}
	if len(persona.Claude.Tools) > 0 {
		sb.WriteString("tools:\n")
		for _, tool := range persona.Claude.Tools {
			sb.WriteString("  - " + tool + "\n")
		}
	}
	sb.WriteString("---\n\n")
	sb.WriteString("@" + persona.Path + "\n")
	return sb.String()
}

// extractFirstParagraph returns the first non-blank, non-heading line of a markdown file.
// Used to derive an auto-invocation description when none is explicitly set.
func extractFirstParagraph(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		return line
	}
	return ""
}

func (t *ClaudeTranslator) renderSettings(cfg *config.Config) string {
	type settings struct {
		MCPServers map[string]mcpServerJSON `json:"mcpServers"`
	}

	project := projectScopedServers(cfg.MCP.Servers)
	s := settings{MCPServers: make(map[string]mcpServerJSON, len(project))}
	for name, srv := range project {
		s.MCPServers[name] = toMCPJSON(srv)
	}

	data, _ := json.MarshalIndent(s, "", "  ")
	return string(data) + "\n"
}
