package translators

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClineTranslator struct{}

func (t *ClineTranslator) Name() string { return "cline" }

func (t *ClineTranslator) OutputFiles() []string {
	// .roo/ covers mcp.json, rules/, and all generated command files
	return []string{".clinerules", ".roo/"}
}

func (t *ClineTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".clinerules", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("cline rules: %w", err)
	}
	if err := writeFile(projectRoot, ".roo/mcp.json", t.renderMCP(cfg)); err != nil {
		return fmt.Errorf("cline mcp: %w", err)
	}
	if err := writeFile(projectRoot, ".roo/rules/ajolote-sync.md", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("cline slash command: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		content := "# " + cmd.Name + "\n\n" + cmd.Content + "\n"
		if err := writeFile(projectRoot, ".roo/rules/"+cmd.Name+".md", content); err != nil {
			return fmt.Errorf("cline command %s: %w", cmd.Name, err)
		}
	}
	return nil
}

func (t *ClineTranslator) Import(projectRoot string) (*ImportResult, error) {
	servers, err := parseMCPFile(filepath.Join(projectRoot, ".roo", "mcp.json"))
	if err != nil {
		return nil, err
	}
	if servers == nil {
		return nil, nil
	}
	return &ImportResult{NewMCPServers: servers}, nil
}

func (t *ClineTranslator) renderSlashCommand() string {
	return `# ajolote-sync

When the user asks to sync or run ajolote-sync, execute the following shell command:

` + "```" + `sh
ajolote sync cline
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .roo/mcp.json into .agents/config.json
- ↓ Regenerates .clinerules and .roo/mcp.json from the updated canonical config

If .agents/config.json was updated, tell the user to review and commit it.
`
}

func (t *ClineTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# Agent Rules\n")
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString(fmt.Sprintf("Project: %s | Stack: %s | Language: %s | Test runner: %s\n\n", cfg.Project.Name, cfg.Project.Stack, cfg.Project.Language, cfg.Project.TestRunner))
	sb.WriteString(rulesMarkdown(cfg))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}

func (t *ClineTranslator) renderMCP(cfg *config.Config) string {
	type mcpFile struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	m := mcpFile{MCPServers: cfg.MCP.Servers}
	if m.MCPServers == nil {
		m.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data) + "\n"
}
