package translators

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClineTranslator struct{}

func (t *ClineTranslator) Name() string { return "cline" }

func (t *ClineTranslator) OutputFiles() []string {
	// .roo/ covers mcp.json, rules/, and all generated command files
	return []string{".clinerules", ".roo/"}
}

func (t *ClineTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".clinerules", t.renderRules(cfg, projectRoot)); err != nil {
		return fmt.Errorf("cline rules: %w", err)
	}
	if err := writeFile(projectRoot, ".roo/mcp.json", t.renderMCP(cfg)); err != nil {
		return fmt.Errorf("cline mcp: %w", err)
	}
	if err := writeFile(projectRoot, ".roo/rules/ajolote-sync.md", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("cline slash command: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		content := "# " + cmd.Name + "\n\n" + cmd.Content + "\n"
		if err := writeFile(projectRoot, ".roo/rules/"+cmd.Name+".md", content); err != nil {
			return fmt.Errorf("cline command %s: %w", cmd.Name, err)
		}
	}
	for _, sr := range cfg.ScopedRules {
		data, _ := os.ReadFile(filepath.Join(projectRoot, sr.Path))
		content := "# " + sr.Name + "\n\n" + strings.TrimSpace(string(data)) + "\n"
		if err := writeFile(projectRoot, ".roo/rules/"+sr.Name+".md", content); err != nil {
			return fmt.Errorf("cline scoped rule %s: %w", sr.Name, err)
		}
	}
	return nil
}

func (t *ClineTranslator) Import(projectRoot string) (*ImportResult, error) {
	rooDir := filepath.Join(projectRoot, ".roo")
	clinerules := filepath.Join(projectRoot, ".clinerules")

	_, rooDirErr := os.Stat(rooDir)
	_, clinerErr := os.Stat(clinerules)
	if os.IsNotExist(rooDirErr) && os.IsNotExist(clinerErr) {
		return nil, nil // Cline not present in this project
	}

	result := &ImportResult{}

	if !os.IsNotExist(rooDirErr) {
		servers, err := parseMCPFile(filepath.Join(rooDir, "mcp.json"))
		if err != nil {
			return nil, err
		}
		result.NewMCPServers = servers

		existing, err := existingCommandNames(projectRoot)
		if err != nil {
			return nil, err
		}

		skip := map[string]bool{"ajolote-sync": true}
		cmds, err := importCommandFiles(filepath.Join(rooDir, "rules"), ".md", skip, existing, func(name, raw string) Command {
			body := strings.TrimPrefix(raw, "# "+name+"\n\n")
			return Command{Name: name, Content: strings.TrimSpace(body)}
		})
		if err != nil {
			return nil, err
		}
		result.NewCommands = cmds
	}

	// Import .clinerules content as a rule file if it was not generated by ajolote
	if !os.IsNotExist(clinerErr) {
		data, err := os.ReadFile(clinerules)
		if err != nil {
			return nil, fmt.Errorf("reading .clinerules: %w", err)
		}
		if content := string(data); !isAjoloteGenerated(content) {
			result.NewRuleFiles = map[string]string{"general.md": content}
		}
	}

	return result, nil
}

func (t *ClineTranslator) renderSlashCommand() string {
	return `# ajolote-sync

When the user asks to sync or run ajolote-sync, execute the following shell command:

` + "```" + `sh
ajolote sync cline
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .roo/mcp.json into .agents/config.json
- ↓ Regenerates .clinerules and .roo/mcp.json from the updated canonical config

If .agents/config.json was updated, tell the user to review and commit it.
`
}

func (t *ClineTranslator) renderRules(cfg *config.Config, projectRoot string) string {
	var sb strings.Builder
	sb.WriteString("# Agent Rules\n")
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString(inlineFiles("Rules", projectRoot, cfg.Rules))
	sb.WriteString(inlineFiles("Skills", projectRoot, cfg.Skills))
	sb.WriteString(inlineFiles("Personas", projectRoot, cfg.Personas))
	sb.WriteString(inlineFiles("Context", projectRoot, cfg.Context))
	return sb.String()
}

func (t *ClineTranslator) renderMCP(cfg *config.Config) string {
	type mcpFile struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	m := mcpFile{MCPServers: cfg.MCP.Servers}
	if m.MCPServers == nil {
		m.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data) + "\n"
}
