package translators

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type ClineTranslator struct{}

func (t *ClineTranslator) Name() string { return "cline" }

func (t *ClineTranslator) OutputFiles() []string {
	return []string{".clinerules", ".roo/mcp.json"}
}

func (t *ClineTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".clinerules", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("cline rules: %w", err)
	}
	if err := writeFile(projectRoot, ".roo/mcp.json", t.renderMCP(cfg)); err != nil {
		return fmt.Errorf("cline mcp: %w", err)
	}
	return nil
}

func (t *ClineTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# Agent Rules\n")
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString(fmt.Sprintf("Project: %s | Stack: %s | Language: %s | Test runner: %s\n\n", cfg.Project.Name, cfg.Project.Stack, cfg.Project.Language, cfg.Project.TestRunner))
	sb.WriteString(rulesMarkdown(cfg))
	return sb.String()
}

func (t *ClineTranslator) renderMCP(cfg *config.Config) string {
	type mcpFile struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	m := mcpFile{MCPServers: cfg.MCP.Servers}
	if m.MCPServers == nil {
		m.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data) + "\n"
}
