package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type CodexTranslator struct{}

func (t *CodexTranslator) Name() string { return "codex" }

func (t *CodexTranslator) OutputFiles() []string {
	return []string{"AGENTS.md"}
}

func (t *CodexTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "AGENTS.md", t.renderAGENTSmd(cfg, projectRoot)); err != nil {
		return fmt.Errorf("codex: %w", err)
	}
	if servers := projectScopedServers(cfg.MCP.Servers); len(servers) > 0 {
		if err := writeFile(projectRoot, ".codex/config.toml", t.renderTOML(servers)); err != nil {
			return fmt.Errorf("codex MCP config: %w", err)
		}
	}
	return nil
}

func (t *CodexTranslator) Import(projectRoot string) (*ImportResult, error) {
	agentsMD := filepath.Join(projectRoot, "AGENTS.md")
	data, err := os.ReadFile(agentsMD)
	if err != nil {
		if os.IsNotExist(err) {
			return &ImportResult{}, nil
		}
		return nil, fmt.Errorf("reading AGENTS.md: %w", err)
	}
	content := string(data)
	if isAjoloteGenerated(content) {
		return &ImportResult{}, nil
	}
	return &ImportResult{
		NewRuleFiles: map[string]string{"general.md": content},
	}, nil
}

func (t *CodexTranslator) renderAGENTSmd(cfg *config.Config, projectRoot string) string {
	var sb strings.Builder
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(inlineFiles("Rules", projectRoot, cfg.Rules))
	sb.WriteString(inlineFiles("Skills", projectRoot, cfg.Skills))
	sb.WriteString(inlineFiles("Personas", projectRoot, personaPaths(cfg.Personas)))
	sb.WriteString(inlineFiles("Context", projectRoot, cfg.Context))
	return sb.String()
}

// renderTOML produces a hand-rolled TOML config for Codex's .codex/config.toml.
// Servers are written in sorted order for deterministic output.
func (t *CodexTranslator) renderTOML(servers map[string]config.MCPServer) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	sb.WriteString("[mcp]\n")

	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		srv := servers[name]
		sb.WriteString(fmt.Sprintf("\n[mcp.servers.%s]\n", name))
		if srv.Command != "" {
			sb.WriteString(fmt.Sprintf("command = %q\n", srv.Command))
		}
		if srv.Transport != "" {
			sb.WriteString(fmt.Sprintf("transport = %q\n", srv.Transport))
		}
		if srv.URL != "" {
			sb.WriteString(fmt.Sprintf("url = %q\n", srv.URL))
		}
		if len(srv.Args) > 0 {
			quoted := make([]string, len(srv.Args))
			for i, a := range srv.Args {
				quoted[i] = fmt.Sprintf("%q", a)
			}
			sb.WriteString(fmt.Sprintf("args = [%s]\n", strings.Join(quoted, ", ")))
		}
		if len(srv.Env) > 0 {
			sb.WriteString(fmt.Sprintf("\n[mcp.servers.%s.env]\n", name))
			envKeys := make([]string, 0, len(srv.Env))
			for k := range srv.Env {
				envKeys = append(envKeys, k)
			}
			sort.Strings(envKeys)
			for _, k := range envKeys {
				sb.WriteString(fmt.Sprintf("%s = %q\n", k, srv.Env[k]))
			}
		}
	}
	return sb.String()
}
