package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

// CodexTranslator handles Codex CLI's .codex/config.toml for MCP server configuration.
// Codex reads AGENTS.md natively — that file is owned by the agents-md translator and
// committed to git alongside .agents/. This translator only manages codex-specific config.
type CodexTranslator struct{}

func (t *CodexTranslator) Name() string { return "codex" }

func (t *CodexTranslator) OutputFiles() []string {
	return []string{".codex/config.toml"}
}

func (t *CodexTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".codex/config.toml", t.renderTOML(projectScopedServers(cfg.MCP.Servers))); err != nil {
		return fmt.Errorf("codex: %w", err)
	}
	return nil
}

// Import reads an existing AGENTS.md (if user-authored) and parses
// .codex/config.toml for any project-scoped MCP servers. Either source can
// bootstrap the canonical config on first use or pick up servers added
// directly to the TOML after initial setup.
func (t *CodexTranslator) Import(projectRoot string) (*ImportResult, error) {
	result := &ImportResult{}

	// Bootstrap from a user-authored AGENTS.md.
	agentsMD := filepath.Join(projectRoot, "AGENTS.md")
	if data, err := os.ReadFile(agentsMD); err == nil {
		if content := string(data); !isAjoloteGenerated(content) {
			result.NewRuleFiles = map[string]string{"general.md": content}
		}
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("reading AGENTS.md: %w", err)
	}

	// Import project-scoped MCP servers from .codex/config.toml.
	// We do NOT filter by isAjoloteGenerated here: the file is always generated
	// but users may add new servers directly, and we want to pick those up.
	servers, err := parseCodexTOML(filepath.Join(projectRoot, ".codex", "config.toml"))
	if err != nil {
		return nil, err
	}
	if len(servers) > 0 {
		result.NewMCPServers = servers
	}

	return result, nil
}

// renderTOML produces a hand-rolled TOML config for Codex's .codex/config.toml.
// Servers are written in sorted order for deterministic output. Always includes
// at least the file header so the translator is detectable on disk.
func (t *CodexTranslator) renderTOML(servers map[string]config.MCPServer) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ajolote-ai from .agents/config.json — do not edit manually\n\n")
	if len(servers) == 0 {
		return sb.String()
	}

	sb.WriteString("[mcp]\n")

	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		srv := servers[name]
		sb.WriteString(fmt.Sprintf("\n[mcp.servers.%s]\n", name))
		if srv.Command != "" {
			sb.WriteString(fmt.Sprintf("command = %q\n", srv.Command))
		}
		if srv.Transport != "" {
			sb.WriteString(fmt.Sprintf("transport = %q\n", srv.Transport))
		}
		if srv.URL != "" {
			sb.WriteString(fmt.Sprintf("url = %q\n", expandEnv(srv.URL)))
		}
		if len(srv.Args) > 0 {
			quoted := make([]string, len(srv.Args))
			for i, a := range srv.Args {
				quoted[i] = fmt.Sprintf("%q", a)
			}
			sb.WriteString(fmt.Sprintf("args = [%s]\n", strings.Join(quoted, ", ")))
		}
		if len(srv.Env) > 0 {
			sb.WriteString(fmt.Sprintf("\n[mcp.servers.%s.env]\n", name))
			envKeys := make([]string, 0, len(srv.Env))
			for k := range srv.Env {
				envKeys = append(envKeys, k)
			}
			sort.Strings(envKeys)
			for _, k := range envKeys {
				sb.WriteString(fmt.Sprintf("%s = %q\n", k, expandEnv(srv.Env[k])))
			}
		}
	}
	return sb.String()
}

