package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type CopilotTranslator struct{}

func (t *CopilotTranslator) Name() string { return "copilot" }

func (t *CopilotTranslator) OutputFiles() []string {
	return []string{".github/copilot-instructions.md"}
}

func (t *CopilotTranslator) Import(projectRoot string) (*ImportResult, error) {
	result := &ImportResult{}

	// Import copilot-instructions.md content as a rule file if it was not generated by ajolote
	instrPath := filepath.Join(projectRoot, ".github", "copilot-instructions.md")
	if data, err := os.ReadFile(instrPath); err == nil {
		if content := string(data); !isAjoloteGenerated(content) {
			result.NewRuleFiles = map[string]string{"general.md": content}
		}
	}

	return result, nil
}

func (t *CopilotTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".github/copilot-instructions.md", t.renderInstructions(cfg)); err != nil {
		return fmt.Errorf("copilot: %w", err)
	}
	return nil
}

func (t *CopilotTranslator) renderInstructions(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by ajolote-ai from .agents/config.json — do not edit manually -->\n\n")
	sb.WriteString(fileListMarkdown("Rules", cfg.Rules))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}
