package translators

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type CursorTranslator struct{}

func (t *CursorTranslator) Name() string { return "cursor" }

func (t *CursorTranslator) OutputFiles() []string {
	return []string{".cursor/rules/agents.mdc", ".cursor/mcp.json"}
}

func (t *CursorTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".cursor/rules/agents.mdc", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("cursor rules: %w", err)
	}
	if err := writeFile(projectRoot, ".cursor/mcp.json", t.renderMCP(cfg)); err != nil {
		return fmt.Errorf("cursor mcp: %w", err)
	}
	return nil
}

func (t *CursorTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString("description: Shared agent rules — generated by ajolote-ai, do not edit manually\n")
	sb.WriteString("alwaysApply: true\n")
	sb.WriteString("---\n\n")

	sb.WriteString(fmt.Sprintf("# %s — AI Agent Rules\n\n", cfg.Project.Name))
	sb.WriteString(fmt.Sprintf("**Stack:** %s | **Language:** %s | **Test runner:** %s\n\n", cfg.Project.Stack, cfg.Project.Language, cfg.Project.TestRunner))
	sb.WriteString("---\n\n")
	sb.WriteString(rulesMarkdown(cfg))

	return sb.String()
}

func (t *CursorTranslator) renderMCP(cfg *config.Config) string {
	type mcpFile struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	m := mcpFile{MCPServers: cfg.MCP.Servers}
	if m.MCPServers == nil {
		m.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data) + "\n"
}
