package translators

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type CursorTranslator struct{}

func (t *CursorTranslator) Name() string { return "cursor" }

func (t *CursorTranslator) OutputFiles() []string {
	// .cursor/rules/ covers agents.mdc, ajolote-sync.mdc, and all generated command files
	return []string{".cursor/rules/", ".cursor/mcp.json"}
}

func (t *CursorTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".cursor/rules/agents.mdc", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("cursor rules: %w", err)
	}
	if err := writeFile(projectRoot, ".cursor/mcp.json", t.renderMCP(cfg)); err != nil {
		return fmt.Errorf("cursor mcp: %w", err)
	}
	if err := writeFile(projectRoot, ".cursor/rules/ajolote-sync.mdc", t.renderSlashCommand()); err != nil {
		return fmt.Errorf("cursor slash command: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		content := "---\ndescription: " + cmd.Description + "\nalwaysApply: false\n---\n\n" + cmd.Content + "\n"
		if err := writeFile(projectRoot, ".cursor/rules/"+cmd.Name+".mdc", content); err != nil {
			return fmt.Errorf("cursor command %s: %w", cmd.Name, err)
		}
	}
	return nil
}

func (t *CursorTranslator) Import(projectRoot string) (*ImportResult, error) {
	cursorDir := filepath.Join(projectRoot, ".cursor")
	if _, err := os.Stat(cursorDir); os.IsNotExist(err) {
		return nil, nil // Cursor not present in this project
	}

	servers, err := parseMCPFile(filepath.Join(cursorDir, "mcp.json"))
	if err != nil {
		return nil, err
	}

	existing, err := existingCommandNames(projectRoot)
	if err != nil {
		return nil, err
	}

	skip := map[string]bool{"agents": true, "ajolote-sync": true}
	cmds, err := importCommandFiles(filepath.Join(cursorDir, "rules"), ".mdc", skip, existing, func(name, raw string) Command {
		desc, body := parseFrontmatter(raw)
		return Command{Name: name, Description: desc, Content: body}
	})
	if err != nil {
		return nil, err
	}

	result := &ImportResult{NewMCPServers: servers, NewCommands: cmds}

	// Import agents.mdc content as a rule file if it was not generated by ajolote
	agentsMDC := filepath.Join(cursorDir, "rules", "agents.mdc")
	if data, err := os.ReadFile(agentsMDC); err == nil {
		raw := string(data)
		if !isAjoloteGenerated(raw) {
			result.NewRuleFiles = map[string]string{"general.md": stripFrontmatter(raw)}
		}
	}

	return result, nil
}

func (t *CursorTranslator) renderSlashCommand() string {
	return `---
description: Sync Cursor config with the shared .agents/config.json
alwaysApply: false
---

When the user asks to sync or run ajolote-sync, run the following shell command:

` + "```" + `sh
ajolote sync cursor
` + "```" + `

This runs in two directions:
- ↑ Imports any new MCP servers from .cursor/mcp.json into .agents/config.json
- ↓ Regenerates .cursor/rules/agents.mdc and .cursor/mcp.json from the updated canonical config

If .agents/config.json was updated, tell the user to review and commit it.
`
}

func (t *CursorTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString("description: Shared agent rules — generated by ajolote-ai, do not edit manually\n")
	sb.WriteString("alwaysApply: true\n")
	sb.WriteString("---\n\n")
	sb.WriteString(fileListMarkdown("Rules", cfg.Rules))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}

func (t *CursorTranslator) renderMCP(cfg *config.Config) string {
	type mcpFile struct {
		MCPServers map[string]config.MCPServer `json:"mcpServers"`
	}

	m := mcpFile{MCPServers: cfg.MCP.Servers}
	if m.MCPServers == nil {
		m.MCPServers = map[string]config.MCPServer{}
	}

	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data) + "\n"
}
