package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type GeminiTranslator struct{}

func (t *GeminiTranslator) Name() string { return "gemini" }

func (t *GeminiTranslator) OutputFiles() []string {
	return []string{"GEMINI.md"}
}

func (t *GeminiTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, "GEMINI.md", t.renderGEMINImd(cfg)); err != nil {
		return fmt.Errorf("gemini: %w", err)
	}
	if userServers := userScopedServers(cfg.MCP.Servers); len(userServers) > 0 {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("resolving home directory: %w", err)
		}
		if err := mergeUserMCPConfig(filepath.Join(home, ".gemini", "settings.json"), userServers); err != nil {
			return fmt.Errorf("writing user MCP config (~/.gemini/settings.json): %w", err)
		}
	}
	return nil
}

func (t *GeminiTranslator) Import(projectRoot string) (*ImportResult, error) {
	geminiMD := filepath.Join(projectRoot, "GEMINI.md")
	data, err := os.ReadFile(geminiMD)
	if err != nil {
		if os.IsNotExist(err) {
			return &ImportResult{}, nil
		}
		return nil, fmt.Errorf("reading GEMINI.md: %w", err)
	}
	content := string(data)
	if isAjoloteGenerated(content) {
		return &ImportResult{}, nil
	}
	return &ImportResult{
		NewRuleFiles: map[string]string{"general.md": content},
	}, nil
}

func (t *GeminiTranslator) renderGEMINImd(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("# GEMINI.md\n\n")
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(atFileList("Rules", cfg.Rules))
	sb.WriteString(atFileList("Skills", cfg.Skills))
	sb.WriteString(atFileList("Personas", personaPaths(cfg.Personas)))
	sb.WriteString(atFileList("Context", cfg.Context))
	return sb.String()
}
