package translators

import "github.com/ajolote-ai/ajolote/internal/config"

// ImportResult describes what was found in the tool's existing config files
// that is not yet present in .agents/config.json.
type ImportResult struct {
	// NewMCPServers are servers found in the tool's config but absent from config.mcp.servers.
	NewMCPServers map[string]config.MCPServer
	// NewCommands are command files found in the tool's command directory but absent from .agents/commands/.
	NewCommands []Command
	// NewRuleFiles are rule file contents found in the tool's primary rules file that were
	// authored by the user (not generated by ajolote). Key is the target filename under
	// .agents/rules/ (e.g. "general.md"), value is the file content.
	NewRuleFiles map[string]string
	// NewScopedRules are glob-scoped rules found in the tool's native scoped-rule files
	// (e.g. Cursor .mdc with globs:, Copilot .instructions.md) that are not yet in the config.
	NewScopedRules []config.ScopedRule
	// ScopedRuleContents maps scoped rule name → body content, so the caller can write
	// the rule file with real content instead of a placeholder stub.
	ScopedRuleContents map[string]string
}

// HasChanges reports whether the import found anything new.
func (r *ImportResult) HasChanges() bool {
	return len(r.NewMCPServers) > 0 || len(r.NewCommands) > 0 || len(r.NewRuleFiles) > 0 || len(r.NewScopedRules) > 0
}

// Syncer extends Translator with the ability to read a tool's existing config
// and return anything not yet present in the canonical config.
type Syncer interface {
	Translator
	// Import reads the tool's existing files under projectRoot and returns
	// whatever it found that is not already represented in the canonical config.
	// Returns a non-nil result with no changes (and nil error) when files exist
	// but nothing new was found. Returns nil result when no tool files exist at all.
	Import(projectRoot string) (*ImportResult, error)
}
