package translators

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type WindsurfTranslator struct{}

func (t *WindsurfTranslator) Name() string { return "windsurf" }

func (t *WindsurfTranslator) OutputFiles() []string {
	// directory patterns cover all generated rules and workflow files
	return []string{".windsurf/rules/", ".windsurf/workflows/"}
}

func (t *WindsurfTranslator) Import(projectRoot string) (*ImportResult, error) {
	result := &ImportResult{}

	// Import agents.md content as a rule file if it was not generated by ajolote.
	agentsMD := filepath.Join(projectRoot, ".windsurf", "rules", "agents.md")
	if data, err := os.ReadFile(agentsMD); err == nil {
		if content := string(data); !isAjoloteGenerated(content) {
			result.NewRuleFiles = map[string]string{"general.md": content}
		}
	}

	// Import scoped rules from .windsurf/rules/*.md (files with a globs: frontmatter field).
	// agents.md is skipped because it is either user-authored general rules (handled above)
	// or ajolote-generated (filtered by isAjoloteGenerated).
	rulesDir := filepath.Join(projectRoot, ".windsurf", "rules")
	if entries, err := os.ReadDir(rulesDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || e.Name() == "agents.md" {
				continue
			}
			data, err := os.ReadFile(filepath.Join(rulesDir, e.Name()))
			if err != nil || isAjoloteGenerated(string(data)) {
				continue
			}
			fields, body := parseFrontmatterFull(string(data))
			globStr := fields["globs"]
			if globStr == "" {
				continue // not a scoped rule
			}
			var globs []string
			for _, g := range strings.Split(globStr, ",") {
				if g = strings.TrimSpace(g); g != "" {
					globs = append(globs, g)
				}
			}
			name := strings.TrimSuffix(e.Name(), ".md")
			result.NewScopedRules = append(result.NewScopedRules, config.ScopedRule{
				Name:  name,
				Globs: globs,
				Path:  ".agents/rules/" + name + ".md",
			})
			if result.ScopedRuleContents == nil {
				result.ScopedRuleContents = map[string]string{}
			}
			result.ScopedRuleContents[name] = body
		}
	}

	// Import commands from .windsurf/workflows/*.yaml (skip ajolote-generated files).
	workflowsDir := filepath.Join(projectRoot, ".windsurf", "workflows")
	existing, err := existingCommandNames(projectRoot)
	if err != nil {
		return nil, err
	}
	skip := map[string]bool{"ajolote-sync": true}
	if entries, err := os.ReadDir(workflowsDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".yaml")
			if skip[name] || existing[name] {
				continue
			}
			data, err := os.ReadFile(filepath.Join(workflowsDir, e.Name()))
			if err != nil || isAjoloteGenerated(string(data)) {
				continue
			}
			desc, body := parseWindsurfWorkflow(string(data))
			result.NewCommands = append(result.NewCommands, Command{
				Name:        name,
				Description: desc,
				Content:     body,
			})
		}
	}

	return result, nil
}

func (t *WindsurfTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".windsurf/rules/agents.md", t.renderRules(cfg, projectRoot)); err != nil {
		return fmt.Errorf("windsurf: %w", err)
	}
	if err := writeFile(projectRoot, ".windsurf/workflows/ajolote-sync.yaml", t.renderWorkflow()); err != nil {
		return fmt.Errorf("windsurf workflow: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		content := "name: " + cmd.Name + "\ndescription: " + cmd.Description + "\nsteps:\n  - name: Execute\n    say: |\n"
		for _, line := range strings.Split(cmd.Content, "\n") {
			content += "      " + line + "\n"
		}
		if err := writeFile(projectRoot, ".windsurf/workflows/"+cmd.Name+".yaml", content); err != nil {
			return fmt.Errorf("windsurf command %s: %w", cmd.Name, err)
		}
	}
	for _, sr := range cfg.ScopedRules {
		data, _ := os.ReadFile(filepath.Join(projectRoot, sr.Path))
		content := fmt.Sprintf("---\ndescription: %s\nglobs: %s\nalwaysApply: false\n---\n\n%s\n",
			sr.Name, strings.Join(sr.Globs, ", "), strings.TrimSpace(string(data)))
		if err := writeFile(projectRoot, ".windsurf/rules/"+sr.Name+".md", content); err != nil {
			return fmt.Errorf("windsurf scoped rule %s: %w", sr.Name, err)
		}
	}
	return nil
}

func (t *WindsurfTranslator) renderWorkflow() string {
	return `name: ajolote-sync
description: Sync Windsurf config with the shared .agents/config.json
steps:
  - name: Run sync
    run: ajolote sync windsurf
  - name: Notify
    say: |
      Sync complete. If .agents/config.json was updated, review the changes
      and commit the file so your teammates receive the updates.
`
}

func (t *WindsurfTranslator) renderRules(cfg *config.Config, projectRoot string) string {
	var sb strings.Builder
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(inlineFiles("Rules", projectRoot, cfg.Rules))
	sb.WriteString(inlineFiles("Skills", projectRoot, cfg.Skills))
	sb.WriteString(inlineFiles("Personas", projectRoot, personaPaths(cfg.Personas)))
	sb.WriteString(inlineFiles("Context", projectRoot, cfg.Context))
	return sb.String()
}
