package translators

import (
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type WindsurfTranslator struct{}

func (t *WindsurfTranslator) Name() string { return "windsurf" }

func (t *WindsurfTranslator) OutputFiles() []string {
	// directory patterns cover all generated rules and workflow files
	return []string{".windsurf/rules/", ".windsurf/workflows/"}
}

func (t *WindsurfTranslator) Import(projectRoot string) (*ImportResult, error) {
	return &ImportResult{}, nil // no structured config to import
}

func (t *WindsurfTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".windsurf/rules/agents.md", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("windsurf: %w", err)
	}
	if err := writeFile(projectRoot, ".windsurf/workflows/ajolote-sync.yaml", t.renderWorkflow()); err != nil {
		return fmt.Errorf("windsurf workflow: %w", err)
	}
	cmds, err := readCommands(projectRoot)
	if err != nil {
		return err
	}
	for _, cmd := range cmds {
		content := "name: " + cmd.Name + "\ndescription: " + cmd.Description + "\nsteps:\n  - name: Execute\n    say: |\n"
		for _, line := range strings.Split(cmd.Content, "\n") {
			content += "      " + line + "\n"
		}
		if err := writeFile(projectRoot, ".windsurf/workflows/"+cmd.Name+".yaml", content); err != nil {
			return fmt.Errorf("windsurf command %s: %w", cmd.Name, err)
		}
	}
	return nil
}

func (t *WindsurfTranslator) renderWorkflow() string {
	return `name: ajolote-sync
description: Sync Windsurf config with the shared .agents/config.json
steps:
  - name: Run sync
    run: ajolote sync windsurf
  - name: Notify
    say: |
      Sync complete. If .agents/config.json was updated, review the changes
      and commit the file so your teammates receive the updates.
`
}

func (t *WindsurfTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(fileListMarkdown("Rules", cfg.Rules))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}
