package translators

import (
	"fmt"
	"strings"

	"github.com/ajolote-ai/ajolote/internal/config"
)

type WindsurfTranslator struct{}

func (t *WindsurfTranslator) Name() string { return "windsurf" }

func (t *WindsurfTranslator) OutputFiles() []string {
	return []string{".windsurf/rules/agents.md", ".windsurf/workflows/ajolote-sync.yaml"}
}

func (t *WindsurfTranslator) Import(projectRoot string) (*ImportResult, error) {
	return &ImportResult{}, nil // no structured config to import
}

func (t *WindsurfTranslator) Generate(cfg *config.Config, projectRoot string) error {
	if err := writeFile(projectRoot, ".windsurf/rules/agents.md", t.renderRules(cfg)); err != nil {
		return fmt.Errorf("windsurf: %w", err)
	}
	if err := writeFile(projectRoot, ".windsurf/workflows/ajolote-sync.yaml", t.renderWorkflow()); err != nil {
		return fmt.Errorf("windsurf workflow: %w", err)
	}
	return nil
}

func (t *WindsurfTranslator) renderWorkflow() string {
	return `name: ajolote-sync
description: Sync Windsurf config with the shared .agents/config.json
steps:
  - name: Run sync
    run: ajolote sync windsurf
  - name: Notify
    say: |
      Sync complete. If .agents/config.json was updated, review the changes
      and commit the file so your teammates receive the updates.
`
}

func (t *WindsurfTranslator) renderRules(cfg *config.Config) string {
	var sb strings.Builder
	sb.WriteString("> Generated by ajolote-ai from `.agents/config.json` — do not edit manually.\n\n")
	sb.WriteString(fmt.Sprintf("# %s — AI Agent Rules\n\n", cfg.Project.Name))
	sb.WriteString(fmt.Sprintf("**Stack:** %s | **Language:** %s | **Test runner:** %s\n\n", cfg.Project.Stack, cfg.Project.Language, cfg.Project.TestRunner))
	sb.WriteString("---\n\n")
	sb.WriteString(rulesMarkdown(cfg))
	sb.WriteString(fileListMarkdown("Skills", cfg.Skills))
	sb.WriteString(fileListMarkdown("Personas", cfg.Personas))
	sb.WriteString(fileListMarkdown("Context", cfg.Context))
	return sb.String()
}
